@extends('layouts.admin')
@section('title', 'Deleted Accounts')
@section('content')
<x-admin.page-header title="Deleted accounts" description="Restore soft-deleted clinic and website accounts without losing their history." />
<form class="cardx p-3 mb-3" method="GET"><div class="row g-2"><div class="col-md-6"><input class="form-control" name="q" value="{{ $q }}" placeholder="Search name or email"></div><div class="col-md-4"><select class="form-select" name="type"><option value="">All account types</option><option value="clinic" @selected($type==='clinic')>Staff & Admin</option><option value="website" @selected($type==='website')>Website accounts</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filter</button></div><div class="col-12"><a class="btn btn-outline-secondary" href="{{ route('admin.deleted_accounts.index') }}">Reset filters</a></div></div></form>
<div class="cardx overflow-hidden"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Account</th><th>Type</th><th>Deleted</th><th class="text-end">Action</th></tr></thead><tbody>
@forelse($accounts as $account)<tr><td><div class="fw-bold">{{ $account->name }}</div><div class="small text-muted">{{ $account->email }}</div></td><td>{{ $account->role==='user'?'Website user':ucfirst($account->role) }}</td><td>{{ $account->deleted_at?->timezone(config('app.timezone'))->format('M j, Y g:i A') }}</td><td class="text-end"><form method="POST" action="{{ $account->role==='user' ? route('admin.user_accounts.restore',$account->id) : route('admin.users.restore',$account->id) }}">@csrf<button class="btn btn-sm btn-outline-primary"><i class="fa fa-rotate-left me-1"></i>Restore</button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-muted p-4">No deleted accounts.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $accounts->links() }}</div>
@endsection
