@extends('layouts.admin')
@section('title', 'Clinic overview')

@push('styles')
<style>
.admin-overview{display:grid;gap:16px;min-width:0}.admin-overview>*{min-width:0}.overview-head{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;flex-wrap:wrap}.overview-head h1{font-size:28px;font-weight:700;letter-spacing:-.6px;margin:0}.overview-head p{margin:5px 0 0;color:var(--admin-muted);font-weight:450}.overview-time{color:var(--admin-muted);font-size:12px;font-weight:500}.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.metric{min-width:0;padding:16px;text-decoration:none;color:var(--admin-text);display:flex;justify-content:space-between;gap:12px;transition:border-color .15s,box-shadow .15s}.metric>div{min-width:0}.metric:hover{border-color:#bfdbfe!important;color:var(--admin-text);box-shadow:var(--admin-shadow)!important}.metric-label{color:var(--admin-muted);font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.55px}.metric-value{max-width:100%;overflow:hidden;text-overflow:ellipsis;font-size:26px;font-weight:700;margin-top:5px}.metric-icon{width:40px;height:40px;flex:0 0 40px;border-radius:10px;display:grid;place-items:center;background:#eff6ff;color:var(--admin-primary)}.overview-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(0,.85fr);gap:14px}.panelx{min-width:0;padding:16px}.panel-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.panel-title h2{font-size:15px;font-weight:650;margin:0}.panel-title a{font-size:12px;font-weight:600;text-decoration:none}.clean-list{display:grid;gap:8px}.clean-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:11px;border:1px solid var(--admin-border);border-radius:10px;color:var(--admin-text);text-decoration:none}.clean-row:hover{background:#f8fbff;color:var(--admin-text)}.row-main{font-weight:600}.row-sub{color:var(--admin-muted);font-size:12px;margin-top:2px}.emptyx{padding:20px;text-align:center;color:var(--admin-muted);font-weight:500}.chart-box{height:230px}.status-dot{width:8px;height:8px;border-radius:50%;background:#f59e0b;display:inline-block;margin-right:6px}@media(max-width:1050px){.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.overview-grid{grid-template-columns:minmax(0,1fr)}}@media(max-width:600px){.metric-grid{grid-template-columns:minmax(0,1fr)}.overview-head{align-items:flex-start}.admin-welcome{align-items:flex-start!important;flex-direction:column}}
</style>
@endpush

@section('content')
<div class="admin-overview">
    <div class="overview-head"><div><h1>Clinic overview</h1><p>Monitor daily clinic activity, finances, bookings, and account security.</p></div><div class="overview-time"><i class="fa-regular fa-clock me-1"></i>{{ $now->format('D, M j, Y · g:i A') }} ({{ config('app.timezone') }})</div></div>
    <section class="admin-welcome" aria-labelledby="welcomeTitle"><div><h2 id="welcomeTitle">Welcome back, {{ auth()->user()?->name ?: 'Administrator' }}</h2><p>Review items that need attention, then continue with clinic monitoring.</p></div><a class="btn" href="{{ route('admin.users.edit', auth()->id()) }}"><i class="fa-regular fa-user me-2"></i>Manage my account</a></section>
    <div class="metric-grid">
        <a class="cardx metric" href="{{ route('admin.approvals.index') }}"><div><div class="metric-label">Pending requests</div><div class="metric-value">{{ $pendingRequests }}</div></div><span class="metric-icon"><i class="fa-solid fa-list-check"></i></span></a>
        <a class="cardx metric metric-featured" href="{{ route('admin.analytics.index', ['range'=>'month']) }}"><div><div class="metric-label">Collected this month</div><div class="metric-value">₱{{ number_format($money['month'], 2) }}</div></div><span class="metric-icon"><i class="fa-solid fa-peso-sign"></i></span></a>
        <a class="cardx metric" href="{{ route('admin.analytics.index') }}"><div><div class="metric-label">Known outstanding balance</div><div class="metric-value">₱{{ number_format($money['outstanding'], 2) }}</div>@if($money['incomplete_balances'] ?? 0)<small>{{ $money['incomplete_balances'] }} incomplete, excluded from total ({{ $money['unknown_total_plans'] }} no-total contracts)</small>@endif</div><span class="metric-icon"><i class="fa-solid fa-file-invoice-dollar"></i></span></a>
        <a class="cardx metric" href="{{ route('admin.analytics.index') }}"><div><div class="metric-label">Active installment plans</div><div class="metric-value">{{ $money['active_plans'] }}</div></div><span class="metric-icon"><i class="fa-solid fa-calendar-check"></i></span></a>
        <a class="cardx metric" href="{{ route('admin.patients.index') }}"><div><div class="metric-label">New patients this month</div><div class="metric-value">{{ $newPatients }}</div></div><span class="metric-icon"><i class="fa-solid fa-user-plus"></i></span></a>
        <a class="cardx metric" href="{{ route('admin.activity.index', ['sensitive'=>1]) }}"><div><div class="metric-label">Security alerts</div><div class="metric-value">{{ $securityAlerts }}</div></div><span class="metric-icon"><i class="fa-solid fa-shield-halved"></i></span></a>
    </div>
    <div class="overview-grid">
        <section class="cardx panelx"><div class="panel-title"><h2>Booking requests requiring review</h2><a href="{{ route('admin.approvals.index') }}">Review all</a></div><div class="clean-list">@forelse($oldestRequests as $appointment)<a class="clean-row" href="{{ route('admin.approvals.index') }}"><div><div class="row-main">{{ $appointment->displayPatientName() }} @if($appointment->created_at?->lt($now->copy()->subDay()))<span class="badge text-bg-warning ms-1">Overdue</span>@endif</div><div class="row-sub">{{ $appointment->service?->name ?: 'Treatment not set' }} · {{ $appointment->appointment_date ? \Carbon\Carbon::parse($appointment->appointment_date)->format('M j, Y') : 'Date not set' }}{{ $appointment->appointment_time ? ' at '.\Carbon\Carbon::parse($appointment->appointment_time)->format('g:i A') : ' · Walk-in' }} · {{ $appointment->displayDentistName() }}</div></div><span class="text-primary fw-semibold">Review</span></a>@empty<div class="emptyx">No pending booking requests.</div>@endforelse</div></section>
        <section class="cardx panelx"><div class="panel-title"><h2>Collections · last 7 days</h2><a href="{{ route('admin.analytics.index', ['range'=>7]) }}">Open reports</a></div><div class="chart-box"><canvas id="collectionsChart"></canvas></div></section>
    </div>
    <section class="cardx panelx"><div class="panel-title"><h2>Actionable account alerts</h2><a href="{{ route('admin.users.index') }}">Manage accounts</a></div><div class="clean-list">@forelse($accountAlerts as $alert)<a class="clean-row" href="{{ $alert['url'] }}"><div><div class="row-main"><i class="fa-solid fa-triangle-exclamation text-warning me-2"></i>{{ $alert['title'] }}</div><div class="row-sub">{{ $alert['detail'] }}</div></div><i class="fa-solid fa-chevron-right"></i></a>@empty<div class="emptyx">No account security items need attention.</div>@endforelse</div></section>
    <div class="overview-grid">
        <section class="cardx panelx"><div class="panel-title"><h2>Upcoming appointments</h2><a href="{{ route('admin.appointments.index') }}">View appointments</a></div><div class="clean-list">@forelse($nearestAppointments as $appointment)<a class="clean-row" href="{{ $appointment->patient_id ? route('admin.patients.show',$appointment->patient_id) : route('admin.appointments.index') }}"><div><div class="row-main">{{ $appointment->displayPatientName() }}</div><div class="row-sub">{{ \Carbon\Carbon::parse($appointment->appointment_date)->format('M j, Y') }}{{ $appointment->appointment_time ? ' · '.\Carbon\Carbon::parse($appointment->appointment_time)->format('g:i A') : ' · Walk-in' }} · {{ $appointment->displayDentistName() }}</div></div><span class="badge text-bg-light">{{ ucfirst($appointment->status) }}</span></a>@empty<div class="emptyx">No upcoming active appointments.</div>@endforelse</div></section>
        <section class="cardx panelx"><div class="panel-title"><h2>Recent sensitive activity</h2><a href="{{ route('admin.activity.index', ['sensitive'=>1]) }}">Open activity log</a></div><div class="clean-list">@forelse($recentSensitiveActivity as $log)<a class="clean-row" href="{{ route('admin.activity.index') }}"><div><div class="row-main"><span class="status-dot"></span>{{ $log->description ?: str($log->event)->headline() }}</div><div class="row-sub">{{ $log->user?->name ?: 'Deleted account' }} · {{ $log->created_at?->diffForHumans() }}</div></div></a>@empty<div class="emptyx">No sensitive activity recorded.</div>@endforelse</div></section>
    </div>
</div>
@endsection

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<script>
const adminChart = document.getElementById('collectionsChart');
if (adminChart) new Chart(adminChart,{type:'bar',data:{labels:@json($collectionLabels),datasets:[{data:@json($collectionValues),backgroundColor:'#2563eb',borderRadius:6}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,ticks:{callback:v=>'₱'+Number(v).toLocaleString()}}}}});
</script>
@endpush
